### ISSUE TITLE
generator dies if route is inactive, making geometry

### ISSUE THREAD

**Issue by anthonymobile** [code4jc/buswatcher#19]

**Comment by anthonymobile** [comment]
i think this also happens if it gets a non-numeric route or something. got this output after it ran through up to #99 successfully

> python generator.py --test --tasks hourly

> Traceback (most recent call last):
>   File "generator.py", line 108, in <module>
>     func = locals()[arg](system_map)
>   File "generator.py", line 48, in hourly
>     task_trigger_1 = RouteUpdater(system_map) # refresh route descriptions
>   File "/home/ubuntu/buswatcher/buswatcher/lib/Generators.py", line 43, in __init__
>     self.refresh_routedata(system_map)
>   File "/home/ubuntu/buswatcher/buswatcher/lib/Generators.py", line 152, in refresh_routedata
>     system_map.route_descriptions['routedata'][r]['prettyname'] = r['nm']
> TypeError: list indices must be integers or slices, not dict

**Comment by anthonymobile** [comment]
for instance, route 308 usually kills it. need to add some better error trapping at `TransitSystem.get_single_route_Paths`

**Comment by anthonymobile** [comment]
this is due to seasonal routes, defined in route_configurations.json but not active, so XML is bad, and looping inside `TransitSystem.get_single_route_Paths`
